# Developed by: Eng Mouaz M AlShahmeh
name: tqdr
description: TQDR App # Developed by: Eng Mouaz M AlShahmeh

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.1.0
  provider: ^6.0.0
  http: ^0.13.4
  fluttertoast: ^8.0.8
  path_provider:
  pdf:
  printing:
  qr_flutter:
  step_progress_indicator:
  url_launcher:
  whatsapp_unilink:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf